package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class MenuPeserta extends javax.swing.JPanel {

    /**
     * Creates new form MenuPeserta
     */
    private final Connection conn;
    public MenuPeserta() {
        initComponents();
        conn = koneksi.getConnection ();
        setTabelModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJenisKelamin = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpeserta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        textSearch = new javax.swing.JTextField();
        panelAdd = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btSimpan = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        textNik = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textTempatLhr = new javax.swing.JTextField();
        textTglLhr = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        textNotlpn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textPddkterakhir = new javax.swing.JTextField();
        textTujuan = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(10000, 32767));
        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setPreferredSize(new java.awt.Dimension(1036, 668));

        tbpeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbpeserta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbpesertaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbpeserta);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setText("DATA PESERTA");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data Backup_2.png"))); // NOI18N

        buttonTambah.setBackground(new java.awt.Color(255, 255, 255));
        buttonTambah.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        buttonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Add.png"))); // NOI18N
        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonHapus.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 51, 51));
        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Delete_4.png"))); // NOI18N
        buttonHapus.setText("Hapus");

        buttonBatal.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(255, 0, 51));
        buttonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Cancel.png"))); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        textSearch.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textSearch.setForeground(new java.awt.Color(102, 204, 255));
        textSearch.setText("Search");
        textSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        textSearch.setCaretColor(new java.awt.Color(255, 102, 153));
        textSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(buttonTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTambah)
                            .addComponent(buttonHapus)
                            .addComponent(buttonBatal)))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        panelMain.add(panelView, "card2");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));
        panelAdd.setPreferredSize(new java.awt.Dimension(1036, 668));

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel7.setText("TAMBAH DATA PESERTA");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Data Backup_2.png"))); // NOI18N

        btSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btSimpan.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Save.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 0, 51));
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Cancel.png"))); // NOI18N
        btCancel.setText("Batal");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel5.setText("No.Telpon");

        jLabel6.setText("Alamat");

        jLabel10.setText("Nama");

        jLabel11.setText("Nik");

        jLabel12.setText("Jenis Kelamin");

        jLabel13.setText("Tempat Lahir");

        jLabel15.setText("Tanggal Lahir");

        textId.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textId.setCaretColor(new java.awt.Color(255, 102, 153));
        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        textNik.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textNik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textNik.setCaretColor(new java.awt.Color(255, 102, 153));

        textNama.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textNama.setCaretColor(new java.awt.Color(255, 102, 153));

        textTempatLhr.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textTempatLhr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textTempatLhr.setCaretColor(new java.awt.Color(255, 102, 153));
        textTempatLhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTempatLhrActionPerformed(evt);
            }
        });

        textTglLhr.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textTglLhr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textTglLhr.setCaretColor(new java.awt.Color(255, 102, 153));
        textTglLhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTglLhrActionPerformed(evt);
            }
        });

        textAlamat.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textAlamat.setCaretColor(new java.awt.Color(255, 102, 153));

        textNotlpn.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textNotlpn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textNotlpn.setCaretColor(new java.awt.Color(255, 102, 153));

        jLabel16.setText("Pendidikan Terakhir");

        jLabel19.setText("Tujuan");

        textPddkterakhir.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textPddkterakhir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textPddkterakhir.setCaretColor(new java.awt.Color(255, 102, 153));

        textTujuan.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        textTujuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        textTujuan.setCaretColor(new java.awt.Color(255, 102, 153));
        textTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTujuanActionPerformed(evt);
            }
        });

        rbJenisKelamin.add(rbLaki);
        rbLaki.setText("Laki-Laki");

        rbJenisKelamin.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(130, 130, 130)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(textNik, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(textTempatLhr, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelAddLayout.createSequentialGroup()
                                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(rbLaki)))
                                        .addGap(40, 40, 40)
                                        .addComponent(rbPerempuan))
                                    .addGroup(panelAddLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(textNotlpn, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTglLhr, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPddkterakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(btSimpan)
                                .addGap(116, 116, 116)
                                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTempatLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTglLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNotlpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPddkterakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan)
                    .addComponent(btCancel))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        panelMain.add(panelAdd, "card2");

        add(panelMain, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void tbpesertaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbpesertaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpesertaAncestorAdded

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
         panelMain.removeAll();
        panelMain.add(panelAdd);
        panelMain.repaint();
        panelMain.revalidate();
        
       
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void textSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
     panelMain.removeAll();
     panelMain.add(panelView);
     panelMain.repaint();
     panelMain.revalidate();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void textTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTujuanActionPerformed

    private void textTglLhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTglLhrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTglLhrActionPerformed

    private void textTempatLhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTempatLhrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTempatLhrActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
       showPanel();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        if(btSimpan.getText().equals("SIMPAN"))
        {
            btSimpan.setText("SIMPAN");
        }
        else if(btSimpan.getText().equals("SIMPAN"))
        { 
            insertData();
        }
        else if(btSimpan.getText().equals("PERBARUI"))
        {
            updateData();
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.ButtonGroup rbJenisKelamin;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tbpeserta;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNik;
    private javax.swing.JTextField textNotlpn;
    private javax.swing.JTextField textPddkterakhir;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField textTempatLhr;
    private javax.swing.JTextField textTglLhr;
    private javax.swing.JTextField textTujuan;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        getData((DefaultTableModel) tbpeserta.getModel());
    }
    private void showPanel (){
        panelMain.removeAll();
        panelMain.add(new MenuPeserta());
        panelMain.repaint();
        panelMain.revalidate();
    }
     private void resetForm() {
        textId.setText("");
        textNik.setText("");
        textNama.setText("");
        textTempatLhr.setText("");
        textTglLhr.setText("");
        rbJenisKelamin.clearSelection();
        textAlamat.setText("");
        textNotlpn.setText("");
        textPddkterakhir.setText("");
        textTujuan.setText("");
        
    }

    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tbpeserta.getModel();
        model.addColumn("Id");
        model.addColumn("Nik");
        model.addColumn("Nama");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("No Telpon");
        model.addColumn("Pendidikan Terakhir");
        model.addColumn("Tujuan Pelatohan");
        
    }

    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM peserta";
        
            try (PreparedStatement st = conn.prepareStatement(sql)){
                 ResultSet rs = st.executeQuery();
        
        while (rs.next()){
            String IdPeserta = rs.getString("id_peserta");
            String Nik = rs.getString("nik");
            String Nama = rs.getString("nama");
            String TempatLahir = rs.getString("tmpt_lahir");
            String TanggalLahir = rs.getString("tgl_lahir");
            String JenisKelamin = rs.getString("jenis_kelamin");
            String Alamat = rs.getString("alamat");
            String NoTelpon = rs.getString("no_tlpn");
            String PendidikanTerakhir = rs.getString("pddk_terakhir");
            String TujuanPelatihan = rs.getString("tujuan_pelatihan");
            
            
            Object[] Baris ={IdPeserta,Nik,Nama,TempatLahir,TanggalLahir,JenisKelamin,Alamat,NoTelpon,PendidikanTerakhir,TujuanPelatihan};
            model.addRow(Baris);
        }
       }
     } catch (SQLException e){
            Logger.getLogger(MenuPeserta.class.getName()).log(Level.SEVERE,null,e);
        }
       
    }
   

    private void insertData() {
            String IdPeserta = textId.getText();
            String Nik = textNik.getText();
            String Nama = textNama.getText();
            String TempatLahir = textTempatLhr.getText();
            String TanggalLahir = textTglLhr.getText();
            String JenisKelamin;
            if(rbLaki.isSelected()){
                JenisKelamin = rbLaki.getText();
            }else if(rbPerempuan.isSelected()){
                JenisKelamin = rbPerempuan.getText();
            }else {
                JenisKelamin =("");
            }
            String Alamat = textAlamat.getText();
            String NoTelpon = textNotlpn.getText();
            String PendidikanTerakhir = textPddkterakhir.getText();
            String TujuanPelatihan = textTujuan.getText();
            
            if(IdPeserta.isEmpty() || Nik.isEmpty() || Nama.isEmpty() || TempatLahir.isEmpty() || TanggalLahir.isEmpty() || JenisKelamin.isEmpty() || Alamat.isEmpty() || NoTelpon.isEmpty() || PendidikanTerakhir.isEmpty() || TujuanPelatihan.isEmpty()){
                JOptionPane.showMessageDialog(this,"Semua Kolom Harus DIisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                String sql = "INSERT INTO peserta (id_peserta,nik,nama,tmpt_lahir,tgl_lahir,jenis_kelamin,alamat,no_tlpn,pddk_terakhir,tujuan_pelatihan) VALUES (?,?,?,?,?,?,?,?,?,?)";
                try (PreparedStatement st = conn.prepareStatement(sql)){
                    st.setString(1,IdPeserta);
                    st.setString(2,Nik);
                    st.setString(3,Nama);
                    st.setString(4,TempatLahir);
                    st.setString(5,TanggalLahir);
                    st.setString(6,JenisKelamin);
                    st.setString(7,Alamat);
                    st.setString(8,NoTelpon);
                    st.setString(9,PendidikanTerakhir);
                    st.setString(10,TujuanPelatihan);
                    
                    int rowInserted = st.executeUpdate();
                    if(rowInserted > 0){
                        JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                        resetForm();
                        loadData();
                        showPanel();
                    }
                }
            }catch (SQLException e) {
                Logger.getLogger(MenuPeserta.class.getName()).log(Level.SEVERE,null,e);
            }
    }
    private void updateData(){
        
    }
}

