/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Asus
 */
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public MenuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        card_anggota = new javax.swing.JPanel();
        lb_anggota = new javax.swing.JLabel();
        lb_jumlahAnggota = new javax.swing.JLabel();
        lb_iconAnggota = new javax.swing.JLabel();
        card_jeniskursus = new javax.swing.JPanel();
        lb_anggota1 = new javax.swing.JLabel();
        lb_jumlahAnggota1 = new javax.swing.JLabel();
        lb_iconAnggota1 = new javax.swing.JLabel();
        card_pembimbing = new javax.swing.JPanel();
        lb_anggota2 = new javax.swing.JLabel();
        lb_jumlahAnggota2 = new javax.swing.JLabel();
        lb_iconAnggota2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPeserta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1036, 668));

        card_anggota.setBackground(new java.awt.Color(0, 153, 153));

        lb_anggota.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        lb_anggota.setForeground(new java.awt.Color(255, 255, 255));
        lb_anggota.setText("PESERTA");

        lb_jumlahAnggota.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        lb_jumlahAnggota.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahAnggota.setText("12112");

        lb_iconAnggota.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        lb_iconAnggota.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Member_1.png"))); // NOI18N

        javax.swing.GroupLayout card_anggotaLayout = new javax.swing.GroupLayout(card_anggota);
        card_anggota.setLayout(card_anggotaLayout);
        card_anggotaLayout.setHorizontalGroup(
            card_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_anggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(lb_iconAnggota)
                .addContainerGap())
            .addGroup(card_anggotaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lb_jumlahAnggota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_anggotaLayout.setVerticalGroup(
            card_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_anggotaLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lb_anggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_jumlahAnggota)
                .addGap(18, 18, 18))
            .addGroup(card_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconAnggota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card_jeniskursus.setBackground(new java.awt.Color(0, 153, 153));

        lb_anggota1.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        lb_anggota1.setForeground(new java.awt.Color(255, 255, 255));
        lb_anggota1.setText("JENIS KURSUS");

        lb_jumlahAnggota1.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        lb_jumlahAnggota1.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahAnggota1.setText("12112");

        lb_iconAnggota1.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        lb_iconAnggota1.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconAnggota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Course Assign.png"))); // NOI18N

        javax.swing.GroupLayout card_jeniskursusLayout = new javax.swing.GroupLayout(card_jeniskursus);
        card_jeniskursus.setLayout(card_jeniskursusLayout);
        card_jeniskursusLayout.setHorizontalGroup(
            card_jeniskursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_jeniskursusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_anggota1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lb_iconAnggota1)
                .addContainerGap())
            .addGroup(card_jeniskursusLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lb_jumlahAnggota1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_jeniskursusLayout.setVerticalGroup(
            card_jeniskursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_jeniskursusLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lb_anggota1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_jumlahAnggota1)
                .addGap(18, 18, 18))
            .addGroup(card_jeniskursusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconAnggota1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card_pembimbing.setBackground(new java.awt.Color(0, 153, 153));

        lb_anggota2.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        lb_anggota2.setForeground(new java.awt.Color(255, 255, 255));
        lb_anggota2.setText("PEMBIMBING");

        lb_jumlahAnggota2.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        lb_jumlahAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahAnggota2.setText("12112");

        lb_iconAnggota2.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        lb_iconAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconAnggota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Teacher.png"))); // NOI18N

        javax.swing.GroupLayout card_pembimbingLayout = new javax.swing.GroupLayout(card_pembimbing);
        card_pembimbing.setLayout(card_pembimbingLayout);
        card_pembimbingLayout.setHorizontalGroup(
            card_pembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_pembimbingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_anggota2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lb_iconAnggota2)
                .addContainerGap())
            .addGroup(card_pembimbingLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lb_jumlahAnggota2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_pembimbingLayout.setVerticalGroup(
            card_pembimbingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_pembimbingLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lb_anggota2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_jumlahAnggota2)
                .addGap(18, 18, 18))
            .addGroup(card_pembimbingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconAnggota2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbPeserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPeserta);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel1.setText("DATA PESERTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(card_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(card_jeniskursus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(card_pembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(card_pembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card_jeniskursus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card_anggota;
    private javax.swing.JPanel card_jeniskursus;
    private javax.swing.JPanel card_pembimbing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_anggota;
    private javax.swing.JLabel lb_anggota1;
    private javax.swing.JLabel lb_anggota2;
    private javax.swing.JLabel lb_iconAnggota;
    private javax.swing.JLabel lb_iconAnggota1;
    private javax.swing.JLabel lb_iconAnggota2;
    private javax.swing.JLabel lb_jumlahAnggota;
    private javax.swing.JLabel lb_jumlahAnggota1;
    private javax.swing.JLabel lb_jumlahAnggota2;
    private javax.swing.JTable tbPeserta;
    // End of variables declaration//GEN-END:variables
}
